name: Java Build

on:
  push:
    branches:
      - main  # 触发分支（根据您的需求修改）

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # 检出存储库

    - name: Set up JDK 11.0.4
      uses: actions/setup-java@v2  # 设置Java版本
      with:
        java-version: '11.0.4'  # 使用Java 11，根据您的需求更改版本

    - name: Build with Maven
      run: mvn clean install  # 运行Maven构建命令，通常是clean install
